const Discord = require("discord.js");
const errors = require("../utils/errors.js");

module.exports.run = async (bot, message, args) => {
    message.delete().catch(O_o=>{});
    let commandsUser = message.author;
    try {
      commandsUser.send({embed: {
        color: 10181046,
        title: "Command List",
        description: "List of usable commands\n```Do not respond to PMs, I will not reply.```",
        author: {
          name: 'Shinobu Oshino',
          icon_url: 'https://i.imgur.com/ajdKcrD.png'
        },
        thumbail: {
          url: 'https://i.imgur.com/ajdKcrD.png'
        },
        fields: [{
            name: ".anidb",
            value: "Link AniDB group page",
            inline: true
          },
          {
            name: ".anidex",
            value: "Link AniDex group page",
            inline: true
          },
          {
            name: ".bluraycollection",
            value: "Link RH's BluRay Collection",
            inline: true
          },
          {
            name: ".irc",
            value: "Link IRC channel",
            inline: true
          },
          {
            name: ".nyaa",
            value: "Link Nyaa page",
            inline: true
          },
          {
            name: ".site",
            value: "Link website",
            inline: true
          },
          {
            name: ".xdcc",
            value: "Link XDCC packlist",
            inline: true
          },
          {
            name: ".xdcchowto",
            value: "How To Use XDCC",
            inline: true
          },
          {
            name: ".admincommands",
            value: "List admin commands",
            inline: true
          }
        ],
        timestamp: new Date(),
        footer: {
            icon_url: message.author.avatarURL,
            text: 'Message generated by ' + message.author.username
        }
      }
    });
  } catch (e) {
    console.log(e.stack);
    message.channel.send('Command list is only sent via DMs, and your DMs are locked, ' + commandsUser)
  }
}

module.exports.help = {
    name: "commands"
}